# Local profile
spring:
  redis:
    host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


server:
  port: 8080

external:
  api:
    greengrocer:
      url: api.postype.net
